name: OpenCV Project CI on Windows

on: 
  push:
    branches: [main]   # Fixed the extra colon here
  pull_request:
    branches: [main]   # Fixed the extra colon here

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository   # Proper indentation
      uses: actions/checkout@v2

    - name: Set up Python 3.12.4      # Proper indentation
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'      # Correct indentation for 'with'

    - name: Install dependencies   # Proper indentation
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install opencv-python

    - name: Run tests              # Proper indentation
      run: |
        main