name: OpenCV Project CI on Docker

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: python:3.12.6

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install dependencies and run tests
      run: |
        python -m pip install --upgrade pip && \
        pip install -r requirements.txt && \
        pytest tests/  # Runs tests only if dependencies install successfully

    - name: Execute main.ipynb
      if: ${{ success() }}   # Runs only if previous step was successful
      run: |
        jupyter nbconvert --to notebook --execute main.ipynb --output output.ipynb