name: OpenCV Project CI on Docker

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        docker build -t my-python-app .
        docker run -v ${{ github.workspace }}:/app my-python-app

    - name: Install dependencies and run tests
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pytest tests/  # Run pytest on the tests directory

    - name: Execute main.ipynb
      if: ${{ success() }}   # Runs only if previous step was successful
      run: |
        jupyter nbconvert --to notebook --execute main.ipynb --output output.ipynb