name: OpenCV Project CI on Docker

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: python:3.12.6

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      continue-on-error: false  # Stop on error

    - name: Check installation status
      if: failure()
      run: |
        echo "Dependency installation failed. Please check requirements.txt for any issues."


    - name: Run tests
      run: |
        pytest tests/   # Run all tests in the tests directory

    - name: Execute main.ipynb
      if: ${{ success() }}   # Only runs if previous steps were successful
      run: |
        jupyter nbconvert --to notebook --execute main.ipynb --output output.ipynb